# Generated by Django 4.2.15 on 2024-08-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='board',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['-updated'], name='boards_boar_updated_ac9c67_idx'),
        ),
    ]
