# Generated by Django 4.2.15 on 2024-08-11 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0003_board_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='begins',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='ends',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
