# Generated by Django 4.2.15 on 2024-08-11 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_board_begins_alter_board_ends_alter_board_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
